version: "3.6"

services:

  # Нужен для общения с сервисами через AMQP, WS протоколы. 
  rabbitmq: 
    container_name: ${PROJECT_NAME}-rabbitmq
    image: ${RABBITMQ_TAG:-bitnami/rabbitmq:latest}
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      RABBITMQ_PLUGINS: rabbitmq_management,rabbitmq_consistent_hash_exchange
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGER_PORT:-15672}:15672
      # Нужен для работы сервисов, которые взаимодействуют с базой данных
# На данном шаге нужен только для auth-service
  database:
    container_name: ${PROJECT_NAME}-database
    image: egalbox/postgres:2.0.0
    restart: always
    ports:
      - ${RABBITMQ_PORT:-5432}:5432
    environment:
      POSTGRES_MULTIPLE_DATABASES: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}

  auth-service:
    container_name: ${PROJECT_NAME}-auth-service
    image: egalbox/auth-service:2.0.0beta20
    environment:
      APP_SERVICE_NAME: auth
      APP_SERVICE_KEY: uZsLnAJz35FWUTVx@eg#Xirv6I*jcw2Y
      DB_HOST: ${PROJECT_NAME}-database
      DB_PASSWORD: ${DATABASE_PASSWORD:-password}
      RABBITMQ_HOST: ${PROJECT_NAME}-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      WAIT_HOSTS: ${PROJECT_NAME}-rabbitmq:5672, ${PROJECT_NAME}-database:5432
    depends_on:
      - rabbitmq
      - database
      # Нужен для работы сервисов, которые взаимодействуют с базой данных
# На данном шаге нужен только для auth-service
# Если уже есть database - можно добавить название новой базы данных в POSTGRES_MULTIPLE_DATABASES переменной через запятую
  database:
    container_name: ${PROJECT_NAME}-database
    image: egalbox/postgres:2.0.0
    restart: always
    ports:
      - ${RABBITMQ_PORT:-5432}:5432
    environment:
      POSTGRES_MULTIPLE_DATABASES: monolit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}

  monolit-service:
    volumes:
      - /home/marina/Develop/monolit-sertvice:/app
    container_name: ${PROJECT_NAME}-monolit-service
    build:
      context: monolit-service
    environment:
      APP_SERVICE_NAME: monolit
      APP_SERVICE_KEY: uiA3ZsU#x@ecwgJrv6ITjLV*nzX5FW2Y
      DB_HOST: ${PROJECT_NAME}-database
      DB_PASSWORD: ${DATABASE_PASSWORD:-password}
      RABBITMQ_HOST: ${PROJECT_NAME}-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      WAIT_HOSTS: ${PROJECT_NAME}-rabbitmq:5672, ${PROJECT_NAME}-database:5432
    depends_on:
      - rabbitmq
      - database


  # Нужен для общения с сервисами через HTTP протокол.
  web-service: 
    container_name: ${PROJECT_NAME}-web-service
    image: egalbox/web-service:2.0.0beta19
    ports:
      - ${WEB_SERVICE_PORT:-80}:8080
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      APP_SERVICE_NAME: web
      RABBITMQ_HOST: ${PROJECT_NAME}-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      WAIT_HOSTS: ${PROJECT_NAME}-rabbitmq:5672
    depends_on:
      - rabbitmq
      
    #  CMD 
